version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: mysql-spark
    restart: always
    environment:
      MYSQL_DATABASE: 'training'
      # So you don't have to use root, but you can if you like
#      MYSQL_USER: 'root'
      # You can use whatever password you like
#      MYSQL_PASSWORD: 'mysqlpass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'mysqlpass'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-db:/var/lib/mysql
  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench-spark
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - workbenchnew:/config
    ports:
      - 3000:3000
      - 3001:3001
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
# Names our volume
volumes:
  mysql-db:
  workbenchnew: