version: "3"

services:

  jupyter-notebook:
    hostname: jupyter-notebook
    container_name: jupyter-notebook
    image: dimajix/jupyter-spark:latest
    command: notebook
    build:
      context:  .
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        notebook-dir: /mnt/notebooks
    env_file:
      - docker-compose.env
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - JUPYTER_PATH=/mnt/notebooks
    expose:
      - 8888
    ports:
      - 8888:8888
    volumes:
      - ./dockervolumes/notebooks:/mnt/notebooks

  spark-master:
    hostname: spark-master
    container_name: jupyter-spark-master
    image: dimajix/jupyter-spark:latest
    command: master
    env_file:
      - docker-compose.env
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
    expose:
      - 6066
      - 7077
      - 9090
    ports:
      - 6066:6066
      - 7077:7077
      - 9090:9090

  spark-exec-1:
    hostname: spark-exec-1
    container_name: jupyter-spark-exec-1
    image: dimajix/jupyter-spark:latest
    command: slave
    env_file:
      - docker-compose.env
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
    expose:
      - 9090
    ports:
      - 9091:9090

  spark-exec-2:
    hostname: spark-exec-2
    container_name: jupyter-spark-exec-2
    image: dimajix/jupyter-spark:latest
    command: slave
    env_file:
      - docker-compose.env
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
    expose:
      - 9090
    ports:
      - 9092:9090